(function() {
	const PREFIX = 'buttCustom_';
	const PAGE_INDEX = 22;

	/*
	 * onMessage
	 * This event is generated by the connection (WebSocket) object.
	 */
	function onMessage(message) {
		var msgObject;

		try {
			msgObject = JSON.parse(message.data);
		} catch (ex) {
			return;
		}

		welcomeDebug(msgObject);

		// Check for dbkeysresult queries
		if (panelHasQuery(msgObject)) {
			//Welcome Settings
			if (panelCheckQuery(msgObject, PREFIX + 'welcomeSettings')) {
				for (var idx in msgObject['results']) {
					var key = msgObject['results'][idx]['key'];
					var val = msgObject['results'][idx]['value'];

					welcomeUpdatePanel(key, val);
				}
			}
		}
	}

	function doQuery() {
		welcomeQuery();
	}







	var doDebugWelcome = true;
	const welcomeSettings = [
		'cooldown'
	];

	function welcomeUpdatePanel(key, val) {
		welcomeDebug('welcomeUpdatePanel ' + key + ' ' + val);
		for (var i = 0; i < welcomeSettings.length; i++) {
			welcomeDebug(key + ' ' + welcomeSettings[i]);
			if (panelMatch(key, welcomeSettings[i])) {
				$('#welcome' + welcomeSettings[i]).val(val);
			}
		}
	}

	function welcomeQuery() {
		welcomeDebug('welcomeQuery');
		sendDBKeys(PREFIX + 'welcomeSettings', 'welcomeSettings');

		setTimeout(function () { sendCommand ("reloadwelcome") }, TIMEOUT_WAIT_TIME);
	}

	function welcomeSave() {
		welcomeDebug('welcomeSave');
		welcomeDebug(welcomeSettings.length);
		for (var i = 0; i < welcomeSettings.length; i++) {
			sendDBUpdate(PREFIX + 'welcomeSettings', 'welcomeSettings', welcomeSettings[i], $('#welcome' + welcomeSettings[i]).val());
		}

		setTimeout(function () { welcomeQuery (); }, TIMEOUT_WAIT_TIME);
	}

	function welcomePurgeCooldowns() {
		setTimeout(function () { sendCommand ("welcomepurgecooldowns") }, TIMEOUT_WAIT_TIME);
	}

	function welcomeDebug(prmLine) {
		if (doDebugWelcome) {
			console.log(prmLine);
		}
	}









    // Load the DB items for this panel, wait to ensure that we are connected.
    var interval = setInterval(function() {
        if (isConnected && TABS_INITIALIZED) {
            var active = $('#tabs').tabs('option', 'active');
            if (active == PAGE_INDEX) {
                doQuery();
                clearInterval(interval);
            }
        }
    }, INITIAL_WAIT_TIME);

    // Query the DB every 30 seconds for updates.
    setInterval(function() {
        var active = $('#tabs').tabs('option', 'active');
        if (active == PAGE_INDEX && isConnected && !isInputFocus()) {
            newPanelAlert('Refreshing ButtBot Custom Data', 'success', 1000);
            doQuery();
        }
    }, 30*1000);

	// Import the HTML file for this panel.
	$("#buttCustomPanel").load("/panel/buttCustom.html");

	$.buttCustomOnMessage = onMessage;
	$.buttCustomDoQuery = doQuery;

	$.welcomeSave = welcomeSave;
	$.welcomePurgeCooldowns = welcomePurgeCooldowns;
})();
